package Password

import "testing"

func TestNeedsRehash(t *testing.T) {
	// Test a password generated by PHP with a cost of 12
	var retVal = NeedsRehash("$2y$12$2Ee5HKv6tOYr4lN5AXNU/.AdZ2uNtDe242rWIbJuSeCTfL/Sqgyqi", PASSWORD_DEFAULT)
	if retVal != false {
		t.Fail()
	}

	// Same password with an ambiguous $2a algorithm
	retVal = NeedsRehash("$2a$12$2Ee5HKv6tOYr4lN5AXNU/.AdZ2uNtDe242rWIbJuSeCTfL/Sqgyqi", PASSWORD_DEFAULT)
	if retVal != true {
		t.Fail()
	}

	// Same password, but pretend it was generated with an insecure $2x algorithm
	retVal = NeedsRehash("$2x$12$2Ee5HKv6tOYr4lN5AXNU/.AdZ2uNtDe242rWIbJuSeCTfL/Sqgyqi", PASSWORD_DEFAULT)
	if retVal != true {
		t.Fail()
	}
}
